# Created with YamlCreate.ps1 v2.1.2 $debug=NVS1.5-1-19041-1645
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: composer.composer
PackageVersion: 2.3.5
PackageLocale: en-US
Publisher: Composer
PublisherUrl: https://getcomposer.org/
PublisherSupportUrl: https://github.com/composer/composer/issues
# PrivacyUrl: 
Author: https://github.com/composer/composer/graphs/contributors
PackageName: Composer
PackageUrl: https://getcomposer.org/
License: MIT
LicenseUrl: https://github.com/composer/composer/blob/main/LICENSE
# Copyright: 
# CopyrightUrl: 
ShortDescription: Dependency Manager for PHP
Description: Composer helps you declare, manage, and install dependencies of PHP projects.
Moniker: composer
Tags:
- composer
- php
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
