# Created with YamlCreate.ps1 v2.1.2 $debug=NVS1.5-1-19041-1645
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: composer.composer
PackageVersion: 2.3.5
MinimumOSVersion: 10.0.0.0
InstallerType: exe
InstallModes:
- interactive
UpgradeBehavior: install
Commands:
- composer
ReleaseDate: 2022-04-13
Installers:
- Architecture: neutral
  InstallerUrl: https://getcomposer.org/Composer-Setup.exe
  InstallerSha256: 10826B503BA6823F14893F0627823017EE1778881222EA9960A7E268739D6956
ManifestType: installer
ManifestVersion: 1.1.0
